"""Builds the static GitHub Pages site (docs/) from data/current_menu.json."""

import html
import json
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:760px;margin:0 auto;
padding:16px;color:#222;background:#fafaf7}
h1,h2{color:#2f6b3a} a{color:#2f6b3a}
table{border-collapse:collapse;width:100%;margin:12px 0}
td,th{border:1px solid #ccc;padding:10px;text-align:left;vertical-align:top}
th{background:#e8f0e8}
.btn{display:inline-block;background:#2f6b3a;color:#fff;padding:10px 14px;border-radius:8px;
text-decoration:none;margin:6px 8px 6px 0;font-size:15px}
.btn.alt{background:#8a6d3b}
.card{background:#fff;border:1px solid #ddd;border-radius:10px;padding:14px;margin:12px 0}
.note{background:#fff8e1;border:1px solid #e0c97f;border-radius:8px;padding:10px;margin:10px 0}
small{color:#666}
"""


def esc(s):
    return html.escape(str(s or ""))


def issue_url(repo, title, body=""):
    return (
        f"https://github.com/{repo}/issues/new?"
        + urllib.parse.urlencode({"title": title, "body": body})
    )


def page(title, body_html):
    return f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="manifest" href="manifest.json">
<link rel="apple-touch-icon" href="icon-180.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Salads">
<meta name="theme-color" content="#2f6b3a">
<title>{esc(title)}</title><style>{CSS}</style></head>
<body><p><a href="index.html">← Week overview</a></p>{body_html}
<hr><small>Generated by salad-agent. Buttons open a GitHub issue; the site updates
automatically about a minute after you submit.</small></body></html>"""


def ul(items):
    return "<ul>" + "".join(f"<li>{esc(i)}</li>" for i in items) + "</ul>"


def build(repo):
    plan = json.loads((ROOT / "data" / "current_menu.json").read_text())
    DOCS.mkdir(exist_ok=True)

    # ---------- Day pages ----------
    for item in plan["menu"]:
        day = item["day"]
        subs = (
            f'<div class="note">Substitution: {esc(item["substitutions"])}</div>'
            if item.get("substitutions")
            else ""
        )
        notes = "".join(
            f'<div class="note">💡 {esc(n)}</div>' for n in item.get("agent_notes", [])
        )
        replace_link = issue_url(
            repo,
            f"replace: {day}",
            "Optional: say why (can't find ingredients, not in the mood, etc.) "
            "so the replacement avoids the problem.",
        )
        substitute_link = issue_url(
            repo,
            f"substitute: {day} / REPLACE_WITH_MISSING_INGREDIENT",
            "Edit the title: put the ingredient you're missing after the slash. "
            "You'll get alternatives posted here and on the recipe page.",
        )
        body = f"""
<h1>{esc(day)} — {esc(item["name"])}</h1>
<p><a href="{esc(item["url"])}">Original recipe ↗</a> · Protein: <b>{esc(item["protein"])}</b></p>
{subs}{notes}
<div class="card"><h2>Ingredients</h2>{ul(item.get("ingredients", []))}</div>
<div class="card"><h2>Tonight's steps (&lt;10 min)</h2>{ul(item.get("night_of_steps_list") or [item.get("night_of_steps", "")])}</div>
<a class="btn" href="{replace_link}">🔄 Replace this recipe</a>
<a class="btn alt" href="{substitute_link}">🧂 Missing an ingredient?</a>
"""
        (DOCS / f"{day.lower()}.html").write_text(page(f"{day} — {item['name']}", body))

    # ---------- Index ----------
    rows = "".join(
        f'<tr><td><b><a href="{m["day"].lower()}.html">{esc(m["day"])}</a></b></td>'
        f'<td><a href="{m["day"].lower()}.html">{esc(m["name"])}</a></td>'
        f"<td>{esc(m['protein'])}</td></tr>"
        for m in plan["menu"]
    )
    beans = ul(
        [
            f"{b['bean']} — {b['dried_amount']} dried. Soak: {b['soak']}. "
            f"Cook: {b['cook']}. Used: {', '.join(b['used_in'])}"
            for b in plan.get("bean_schedule", [])
        ]
    )
    sl = plan["shopping_list"]
    body = f"""
<h1>🥗 Week of {esc(plan["week_of"])}</h1>
<table><tr><th>Day</th><th>Salad</th><th>Protein</th></tr>{rows}</table>
<div class="card"><h2>🫘 Bean soak &amp; cook schedule</h2>{beans}</div>
<div class="card"><h2>📋 Weekend prep</h2>
<b>Saturday</b>{ul(plan["weekend_prep"]["saturday"])}
<b>Sunday</b>{ul(plan["weekend_prep"]["sunday"])}</div>
<div class="card"><h2>🛒 Shopping list</h2>
<b>Produce</b>{ul(sl["produce"])}
<b>Dried beans &amp; legumes</b>{ul(sl["dried_beans_legumes"])}
<b>Dairy &amp; other</b>{ul(sl["dairy_and_other"])}
<b>Pantry check</b>{ul(sl["pantry_check"])}</div>
<p>Feedback: <a href="{issue_url(repo, 'favorite: RECIPE_NAME')}">⭐ favorite</a> ·
<a href="{issue_url(repo, 'reject: RECIPE_NAME')}">🚫 reject forever</a>
(edit the recipe name in the title)</p>
"""
    (DOCS / "index.html").write_text(
        page(f"Salad week of {plan['week_of']}", body).replace(
            '<p><a href="index.html">← Week overview</a></p>', ""
        )
    )

    # ---------- today.html: instant redirect to tonight's recipe ----------
    (DOCS / "today.html").write_text(
        """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tonight's salad</title><script>
var d=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"];
location.replace(d[new Date().getDay()] + ".html");
</script></head><body><a href="index.html">Week overview</a></body></html>"""
    )

    # ---------- PWA manifest ----------
    (DOCS / "manifest.json").write_text(
        json.dumps(
            {
                "name": "Salad Agent",
                "short_name": "Salads",
                "start_url": "today.html",
                "display": "standalone",
                "background_color": "#fafaf7",
                "theme_color": "#2f6b3a",
                "icons": [
                    {"src": "icon-180.png", "sizes": "180x180", "type": "image/png"},
                    {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
                ],
            },
            indent=2,
        )
    )
    print(f"Site built: {len(plan['menu'])} day pages + index + today.html")


if __name__ == "__main__":
    import os

    build(os.environ.get("GITHUB_REPOSITORY", "pH-/octo-salad-agent"))
